name = "Chatham Main Line Rochester to Faversham + Medway Valley & Sheerness Lines"
display_name = "Chatham Main Line - Medway Area"
description = "A simulation of the busy Chatham Main Line and surronding branch lines."
rly_file = "ChathamMainLine-Medway.rly"
ttb_files = [ "ChathamMainLine-Medway OffPeak.ttb",]
ssn_files = []
doc_files = [ "readme-ChathamMainLine-Medway",]
img_files = [ "ChathamMainLine-Medway.bmp",]
graphic_files = []
country_code = "GB"
year = 2022
factual = true
difficulty = 3
author = "MissCatTrap"
contributors = []
version = "1.0.0"
release_date = "2022-02-09"
